#!/bin/bash

set -ex

SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)


export CXX=occlum-gcc
export CC=occlum-gcc

cd sqlite_src/sqlite-autoconf-3330000
make && make install
cd $SHELL_FOLDER

rm -rf build
mkdir build
cd build
sudo cmake ..
make

